name: 🛟 提交遇到的问题
description: 提交使用 CatWrt 遇到的问题，需要帮助或者让我们改进
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        首先非常感谢你的反馈，帮助到了 CatWrt 社区排查问题，所有的努力都是值得的!

  - type: textarea
    id: feature_description
    attributes:
      label: 提供 BUG 问题日志
      description: |
        请在 CatWrt 终端上执行 cattools 工具箱，选择 Debug 以收集本次问题的日志. |
        https://www.miaoer.xyz/posts/blog/cattools#Debug%20-%20%E6%8A%93%E5%8F%96%E6%97%A5%E5%BF%97
      placeholder: |
        ## 填写你在设备上的日志信息
      render: markdown

  - type: textarea
    id: prevalence
    attributes:
      label: 问题 BUG 描述
      description: "你是怎么发现 BUG 的，是什么模块/插件/系统导致的问题，具体情况描述，持续时间"
      placeholder: "Example: Whenever I visit the personal account page (1-2 times a week)"

  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: A minimal reproduction of screen recording.
      placeholder: Reproduction
    validations:
      required: true
  
  - type: dropdown
    id: software_version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)

  - type: dropdown
    id: bug_reproducible
    attributes:
      label: BUG 能不能复现
      description: 请选择 BUG 是否能复现
      options:
        - 能复现
        - 不能复现
        - 偶尔能复现

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: 我确认我的 BUG 来自 CatWrt，而不是别的 OpenWrt 固件
          required: true
        - label: 我将遵守 CatWrt 开源社区规范，不将设备为商业目的
          required: true
        - label: 我已确认我的内容反馈内容的正确
          required: true
