name: 🚀 New feature proposal
description: Propose a new feature
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature report!

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: |
        Provide a detailed description of the proposed feature. You can use Markdown syntax to format your text.
      placeholder: |
        ## Feature Title
        - **Motivation**: Why do you want this feature?
        - **Description**: What does this feature do?
        - **Alternatives**: Are there any alternative solutions or features you've considered?
      render: markdown

  - type: text
    id: prevalence
    attributes:
      label: Bug prevalence
      description: "How often do you or others encounter this bug?"
      placeholder: "Example: Whenever I visit the personal account page (1-2 times a week)"
  
  - type: dropdown
    id: software_version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)

  - type: file
    id: log_files
    attributes:
      label: 上传日志文件
      description: 如果有相关的日志文件，请上传以帮助我们更好地排查问题。
      multiple: true

  - type: dropdown
    id: bug_reproducible
    attributes:
      label: BUG 能不能复现
      description: 请选择 BUG 是否能复现
      options:
        - 能复现
        - 不能复现
        - 偶尔能复现

  - type: checkboxes
    id: validations
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following:
      options:
        - label: 我已确认我的内容反馈内容的正确
        - label: 我确认我的 BUG 来自 CatWrt，而不是别的 OpenWrt 固件
