name: Send Email with Attachment

on:
  workflow_dispatch:
    inputs:
      subject:
        description: 'Email Subject'
        required: true
      attachment_path:
        description: 'Path to logs.txt'
        required: true
        default: '/www/logs.txt'

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y msmtp-mta ca-certificates bsd-mailx

    - name: Configure msmtp
      run: |
        echo "account default" > ~/.msmtprc
        echo "host ${{ secrets.SMTP_SERVER }}" >> ~/.msmtprc
        echo "port ${{ secrets.SMTP_PORT }}" >> ~/.msmtprc
        echo "tls on" >> ~/.msmtprc
        echo "auth on" >> ~/.msmtprc
        echo "user ${{ secrets.EMAIL_USERNAME }}" >> ~/.msmtprc
        echo "passwordeval echo ${{ secrets.EMAIL_PASSWORD }}" >> ~/.msmtprc
        echo "from ${{ secrets.EMAIL_USERNAME }}" >> ~/.msmtprc
        chmod 600 ~/.msmtprc

    - name: Send email with attachment
      run: |
        echo "Sending email with subject: ${{ github.event.inputs.subject }}"
        echo "Please see the attached logs." | mailx -s "${{ github.event.inputs.subject }}" -a ${{ github.event.inputs.attachment_path }} ${{ secrets.RECIPIENT_EMAIL }}
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
