name: Send Email with Attachment

on:
  workflow_dispatch:
    inputs:
      subject:
        description: 'Email Subject'
        required: true
      attachment_path:
        description: 'Path to logs.txt'
        required: true
        default: '/www/logs.txt'

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y msmtp-mta ca-certificates bsd-mailx

    - name: Configure msmtp
      run: |
        echo "account default" > ~/.msmtprc
        echo "host $SMTP_SERVER" >> ~/.msmtprc
        echo "port $SMTP_PORT" >> ~/.msmtprc
        echo "tls on" >> ~/.msmtprc
        echo "auth on" >> ~/.msmtprc
        echo "user $EMAIL_USERNAME" >> ~/.msmtprc
        echo "passwordeval echo $EMAIL_PASSWORD" >> ~/.msmtprc
        echo "from $EMAIL_USERNAME" >> ~/.msmtprc
        chmod 600 ~/.msmtprc

    - name: Send email with attachment
      run: |
        echo "Sending email with subject: ${{ github.event.inputs.subject }}"
        msmtp $RECIPIENT_EMAIL < <(echo -e "Subject: ${{ github.event.inputs.subject }}\n\nPlease see the attached logs.\n") \
              -a ${{ github.event.inputs.attachment_path }}
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
